name: 'ReleaseGate Change Risk Analyzer'
description: 'Automated change-risk scoring and enforcement for pull requests'
author: 'Abishek Giri'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  repo:
    description: 'Repository name (owner/repo)'
    required: false
    default: ${{ github.repository }}
  pr:
    description: 'Pull Request Number'
    required: false
    default: ${{ github.event.pull_request.number }}
  mode:
    description: 'Enforcement Mode: report_only (Exit 0 always) or block (Exit 1 on failure)'
    required: false
    default: 'report_only'
  token:
    description: 'GitHub Token for API access'
    required: false
    default: ${{ github.token }}
  config:
    description: 'Path to custom configuration file'
    required: false
    default: 'releasegate.yaml'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - 'analyze-pr'
    - '--repo'
    - ${{ inputs.repo }}
    - '--pr'
    - ${{ inputs.pr }}
    - '--config'
    - ${{ inputs.config }}

  env:
    GITHUB_TOKEN: ${{ inputs.token }}
    RELEASEGATE_ENFORCEMENT: ${{ inputs.mode }}
    COMPLIANCEBOT_ENFORCEMENT: ${{ inputs.mode }}
